default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['ASC_KEY_ID']}.p8"),
      duration: 1200,
      in_house: false
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "/tmp/SpectrumIPA/Spectrum.ipa",
      skip_waiting_for_build_processing: true
    )
  end

  lane :submit do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['ASC_KEY_ID']}.p8"),
      duration: 1200,
      in_house: false
    )

    upload_to_app_store(
      api_key: api_key,
      ipa: "/tmp/SpectrumIPA/Spectrum.ipa",
      submit_for_review: true,
      automatic_release: true,
      force: true,
      skip_screenshots: true,
      skip_metadata: false,
      metadata_path: "./fastlane/metadata",
      precheck_include_in_app_purchases: false
    )
  end
end
