default_platform(:ios)

platform :ios do
  lane :submit do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['ASC_KEY_ID']}.p8"),
      duration: 1200,
      in_house: false
    )

    notes_path = "fastlane/metadata/en-US/release_notes.txt"
    release_notes_text = File.exist?(notes_path) ? File.read(notes_path).strip : "Bug fixes and performance improvements."

    upload_to_app_store(
      api_key: api_key,
      ipa: "/tmp/SpectrumIPA/Spectrum.ipa",
      submit_for_review: true,
      automatic_release: true,
      force: true,
      skip_screenshots: true,
      skip_metadata: true,
      release_notes: { "en-US" => release_notes_text },
      precheck_include_in_app_purchases: false
    )
  end
end
