import { getMedicalReportTranslations } from './translations';
import environment from '../../config/environment';

const FILE_URL = environment.file_url;

/**
 * Generate Visit Confirmation Report HTML matching web PDF format
 * @param {Object} report - Visit confirmation report data
 * @param {boolean} isArabic - RTL language support
 * @param {Object} options - Additional options
 * @returns {Object} { html: string, privateFileIds: Object }
 */
export const generateVisitConfirmationHTML = (report, isArabic = false, options = {}) => {
  const t = getMedicalReportTranslations(isArabic);
  const privateFileIds = {};

  const formatDate = (date) => {
    if (!date) return 'N/A';
    return new Date(date).toLocaleDateString(isArabic ? 'ar-SA' : 'en-US', {
      year: 'numeric',
      month: 'long',
      day: '2-digit'
    });
  };

  const safeString = (value) => {
    if (value === null || value === undefined) return 'N/A';
    if (typeof value === 'string') return value;
    if (typeof value === 'object') {
      return value.nameEnglish || value.name || value.fullName || 'N/A';
    }
    return String(value);
  };

  const isRTL = isArabic;
  const textAlign = isRTL ? 'right' : 'left';
  const direction = isRTL ? 'rtl' : 'ltr';

  // Extract data
  const patient = report?.patient || {};
  const visits = report?.visitConfirmationData?.visits || report?.visits || [];
  const generatedDate = formatDate(report?.createdAt || new Date());

  // Generate visit count text
  const visitCount = visits.length;
  const visitText = isArabic
    ? (visitCount === 1 ? 'قد حضر موعدًا طبيًا' : `قد حضر ${visitCount} مواعيد طبية`)
    : (visitCount === 1 ? 'has attended a medical appointment' : `has attended ${visitCount} medical appointments`);

  // Translation labels
  const labels = {
    title: isArabic ? 'تأكيد الزيارة' : 'Visit Confirmation',
    name: isArabic ? 'الاسم:' : 'Name:',
    dob: isArabic ? 'تاريخ الميلاد:' : 'Date of Birth:',
    id: isArabic ? 'رقم الهوية:' : 'ID:',
    toWhom: isArabic ? 'إلى من يهمه الأمر:' : 'To Whom It May Concern:',
    confirmationText: isArabic
      ? `نؤكد بموجب هذا الخطاب أن المريض المذكور أعلاه ${visitText} في عيادات سبكتروم كما هو موضح أدناه. تمت الزيارة/الزيارات لأغراض الاستشارة الطبية و/أو العلاج.`
      : `This letter is to confirm that the above-named patient ${visitText} at Spectrum Clinics as detailed below. The visit(s) were conducted for medical consultation and/or treatment purposes.`,
    visitDetails: isArabic ? 'تفاصيل الزيارة' : 'Visit Details',
    date: isArabic ? 'التاريخ' : 'Date',
    service: isArabic ? 'الخدمة' : 'Service',
    provider: isArabic ? 'مقدم الخدمة' : 'Provider',
    contactMessage: isArabic
      ? 'لا تتردد في التواصل معنا إذا كان لديك أي استفسارات أو تحتاج إلى معلومات إضافية.'
      : 'Please feel free to contact us if you have any questions or require additional information.',
    regards: isArabic ? 'مع التحية،' : 'Regards,',
    clinicName: isArabic ? 'عيادات سبكتروم' : 'Spectrum Clinics',
    disclaimer: isArabic
      ? `تم إنشاء هذا المستند تلقائيًا بواسطة بوابة مرضى عيادات سبكتروم بتاريخ ${generatedDate}. للتحقق أو الاستفسارات، يرجى التواصل مع عيادات سبكتروم مباشرة.`
      : `This document was automatically generated by the Spectrum Clinics patient portal on ${generatedDate}. For verification or inquiries, please contact Spectrum Clinics directly.`,
  };

  // Generate visits table rows
  const visitsRows = visits.map(visit => `
    <tr>
      <td style="padding: 10px; border-bottom: 1px solid #E5E7EB; text-align: center; font-size: 11px;">
        ${formatDate(visit.date || visit.startTime)}
      </td>
      <td style="padding: 10px; border-bottom: 1px solid #E5E7EB; text-align: center; font-size: 11px;">
        ${visit.service || visit.appointmentType?.name || (isArabic ? 'استشارة طبية' : 'Medical Consultation')}
      </td>
      <td style="padding: 10px; border-bottom: 1px solid #E5E7EB; text-align: center; font-size: 11px;">
        ${isArabic ? 'د. ' : 'Dr. '}${visit.provider?.fullName || visit.providerName || 'N/A'}
      </td>
    </tr>
  `).join('');

  const html = `
    <!DOCTYPE html>
    <html dir="${direction}" lang="${isArabic ? 'ar' : 'en'}">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
      <title>${labels.title}</title>
      <style>
        @page {
          size: A4;
          margin: 10mm;
        }

        @media print {
          html, body {
            width: 210mm;
            min-height: 297mm;
          }
          * {
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }
        }

        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        html {
          background: #f0f0f0;
        }

        body {
          font-family: ${isArabic ? 'Arial, "Noto Sans Arabic", sans-serif' : 'Arial, sans-serif'};
          font-size: 11px;
          line-height: 1.4;
          color: #333;
          background: white;
          direction: ${direction};
          text-align: ${textAlign};
          padding: 15px;
          width: 100%;
          max-width: 210mm;
          min-height: 100vh;
          margin: 0 auto;
          display: flex;
          flex-direction: column;
        }

        .container {
          width: 100%;
          margin: 0 auto;
          background: white;
          flex: 1;
          padding: 0 15px;
        }

        .header-image {
          width: 100%;
          display: block;
          margin-bottom: 15px;
        }

        .footer-image {
          width: 100%;
          display: block;
          margin-top: auto;
          flex-shrink: 0;
        }

        .patient-info {
          margin-bottom: 15px;
        }

        .patient-info p {
          margin: 4px 0;
          font-size: 12px;
        }

        .patient-info strong {
          font-weight: bold;
        }

        .salutation {
          font-size: 12px;
          text-decoration: underline;
          margin: 15px 0;
        }

        .confirmation-text {
          font-size: 11px;
          color: #333;
          line-height: 1.6;
          margin-bottom: 15px;
          text-align: justify;
        }

        .table-title {
          font-size: 13px;
          font-weight: bold;
          text-align: center;
          margin: 20px 0 12px 0;
          color: #333;
        }

        .visit-table {
          width: 100%;
          border-collapse: collapse;
          border: 1px solid #ccc;
          margin-bottom: 15px;
          font-size: 11px;
        }

        .visit-table th {
          background-color: #F5F5F5;
          padding: 10px;
          border-bottom: 1px solid #ccc;
          font-weight: bold;
          text-align: center;
          font-size: 11px;
        }

        .contact-message {
          font-size: 11px;
          margin: 20px 0 8px 0;
        }

        .regards {
          font-size: 11px;
          margin-bottom: 5px;
        }

        .clinic-name {
          font-size: 11px;
          margin-bottom: 20px;
        }

        .disclaimer {
          font-size: 9px;
          color: #666;
          margin-top: 30px;
          padding-top: 15px;
          border-top: 1px solid #E5E5E5;
          text-align: center;
          font-style: italic;
          line-height: 1.4;
        }
      </style>
    </head>
    <body>
      <!-- Header Image -->
      <img src="${FILE_URL}/uploads/app/document-header.png" class="header-image" alt="Header" />

      <div class="container">
        <!-- Patient Information -->
        <div class="patient-info">
          <p><strong>${labels.name}</strong> ${safeString(patient.fullName)}</p>
          <p><strong>${labels.dob}</strong> ${patient.dob ? formatDate(patient.dob) : 'N/A'}</p>
          <p><strong>${labels.id}</strong> ${patient.nationalId || patient.userId || 'N/A'}</p>
        </div>

        <!-- Salutation -->
        <p class="salutation">${labels.toWhom}</p>

        <!-- Confirmation Text -->
        <p class="confirmation-text">${labels.confirmationText}</p>

        <!-- Visit Details Table -->
        <p class="table-title">${labels.visitDetails}</p>

        <table class="visit-table">
          <thead>
            <tr>
              <th style="width: 30%;">${labels.date}</th>
              <th style="width: 40%;">${labels.service}</th>
              <th style="width: 30%;">${labels.provider}</th>
            </tr>
          </thead>
          <tbody>
            ${visitsRows || `<tr><td colspan="3" style="text-align: center; padding: 20px; color: #666;">${isArabic ? 'لا توجد زيارات' : 'No visits found'}</td></tr>`}
          </tbody>
        </table>

        <!-- Contact Message -->
        <p class="contact-message">${labels.contactMessage}</p>
        <p class="regards">${labels.regards}</p>
        <p class="clinic-name">${labels.clinicName}</p>

        <!-- Disclaimer -->
        <p class="disclaimer">${labels.disclaimer}</p>
      </div>

      <!-- Footer Image -->
      <img src="${FILE_URL}/uploads/app/document-footer.png" class="footer-image" alt="Footer" />
    </body>
    </html>
  `;

  return { html, privateFileIds, toString: () => html };
};
